name: pull-request
run-name: ${{ github.actor }} run jobs
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - release
      - main

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Install depencies
        run: npm ci

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Linting
        run: npm run lint

  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3

      - name: Testing
        run: npm run test
